In [ ]:
import pandas as pd
import numpy as np
import os
import pickle

file_path = 'Add_XGB_DNN_Trade-off_overall_data_medical.pkl'
with open(file_path, 'rb') as f:
    medical_df = pickle.load(f)

Mounted at /content/drive

In [ ]:
medical_df['Overall_Overall'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
64,Overall,Overall,CPP,-0.040 (-8.2%),-0.050 (-6.5%),-0.006 (-7.5%),0.080 (40.5%)
65,Overall,Overall,EPP,-0.073 (-13.4%),-0.066 (-8.7%),-0.093 (-48.6%),-0.110 (-56.5%)
70,Overall,Overall,ROC,-0.007 (-1.0%),0.006 (1.1%),-0.081 (-39.1%),-0.070 (-28.8%)
69,Overall,Overall,PSTA,-0.006 (-1.1%),-0.010 (-1.2%),-0.068 (-40.3%),-0.059 (-32.3%)
66,Overall,Overall,FACT,-0.241 (-60.6%),-0.155 (-21.0%),0.093 (85.8%),0.006 (16.0%)
67,Overall,Overall,GSTAR,-0.089 (-15.9%),-0.050 (-6.8%),-0.085 (-35.4%),-0.091 (-31.8%)
68,Overall,Overall,MAB,-0.112 (-37.4%),-0.095 (-13.1%),-0.044 (-31.6%),-0.060 (-43.1%)
71,Overall,Overall,Average,-0.081 (-19.6%),-0.060 (-8.0%),-0.040 (-16.7%),-0.044 (-19.4%)

In [ ]:
medical_df['High_High'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
1,High,High,CPP,-0.083 (-15.5%),-0.054 (-7.5%),-0.002 (-9.7%),-0.043 (-22.9%)
2,High,High,EPP,-0.132 (-24.4%),-0.083 (-11.2%),-0.191 (-68.8%),-0.230 (-78.5%)
7,High,High,ROC,-0.023 (-4.3%),0.014 (2.1%),-0.179 (-64.4%),-0.168 (-51.4%)
6,High,High,PSTA,-0.006 (-0.9%),0.006 (0.9%),-0.082 (-37.7%),-0.062 (-28.8%)
3,High,High,FACT,-0.534 (-99.2%),-0.233 (-31.6%),-0.244 (-98.8%),-0.266 (-99.2%)
4,High,High,GSTAR,-0.185 (-35.0%),-0.104 (-14.2%),-0.191 (-64.2%),-0.223 (-70.1%)
5,High,High,MAB,-0.133 (-24.6%),-0.095 (-12.7%),-0.054 (-23.2%),-0.124 (-44.3%)
8,High,High,Average,-0.157 (-29.1%),-0.078 (-10.6%),-0.135 (-52.4%),-0.159 (-56.4%)

In [ ]:
medical_df['High_Low'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
10,High,Low,CPP,-0.002 (-1.0%),-0.014 (-1.9%),-0.036 (-40.7%),-0.023 (-34.6%)
11,High,Low,EPP,-0.008 (-4.2%),-0.024 (-3.4%),-0.037 (-36.9%),-0.027 (-39.0%)
16,High,Low,ROC,-0.012 (-6.8%),0.005 (0.7%),-0.036 (-43.3%),-0.013 (-13.2%)
15,High,Low,PSTA,-0.001 (-0.7%),-0.000 (0.0%),-0.014 (-35.6%),0.001 (-4.5%)
12,High,Low,FACT,-0.179 (-100.0%),-0.217 (-30.2%),-0.070 (-100.0%),-0.046 (-100.0%)
13,High,Low,GSTAR,-0.002 (-0.9%),-0.011 (-1.6%),0.006 (17.7%),0.009 (42.5%)
14,High,Low,MAB,-0.171 (-95.4%),-0.215 (-30.0%),-0.066 (-92.4%),-0.044 (-94.1%)
17,High,Low,Average,-0.054 (-29.9%),-0.068 (-9.5%),-0.036 (-47.3%),-0.020 (-34.7%)

In [ ]:
medical_df['High_Medium'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
19,High,Medium,CPP,-0.060 (-18.0%),-0.045 (-6.4%),-0.122 (-62.9%),-0.091 (-54.0%)
20,High,Medium,EPP,-0.061 (-18.5%),-0.043 (-6.2%),-0.132 (-71.8%),-0.129 (-80.4%)
25,High,Medium,ROC,0.021 (8.8%),0.032 (5.5%),-0.112 (-61.5%),-0.074 (-37.3%)
24,High,Medium,PSTA,-0.005 (-1.4%),-0.000 (0.0%),-0.104 (-55.3%),-0.079 (-49.2%)
21,High,Medium,FACT,-0.332 (-84.5%),-0.204 (-28.5%),-0.033 (-1.9%),-0.009 (69.7%)
22,High,Medium,GSTAR,-0.078 (-21.6%),-0.051 (-7.3%),-0.130 (-68.4%),-0.118 (-70.8%)
23,High,Medium,MAB,-0.201 (-60.3%),-0.150 (-20.7%),-0.112 (-60.1%),-0.116 (-68.8%)
26,High,Medium,Average,-0.102 (-27.9%),-0.066 (-9.1%),-0.106 (-54.5%),-0.088 (-41.5%)

In [ ]:
medical_df['Low_High'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
28,Low,High,CPP,-0.007 (-0.9%),-0.013 (-1.6%),0.026 (25.3%),0.241 (164.5%)
29,Low,High,EPP,-0.050 (-6.1%),-0.098 (-12.2%),-0.032 (-29.8%),-0.057 (-32.5%)
34,Low,High,ROC,-0.011 (-1.4%),-0.007 (-0.8%),0.020 (21.0%),-0.006 (-1.1%)
33,Low,High,PSTA,-0.010 (-1.3%),-0.035 (-4.4%),-0.011 (-9.6%),-0.041 (-24.6%)
30,Low,High,FACT,-0.091 (-11.0%),-0.058 (-7.2%),0.511 (482.5%),0.256 (164.7%)
31,Low,High,GSTAR,-0.065 (-7.9%),-0.032 (-4.0%),-0.021 (-19.8%),-0.018 (-10.5%)
32,Low,High,MAB,-0.028 (-3.4%),-0.008 (-1.1%),0.023 (23.2%),-0.003 (-1.7%)
35,Low,High,Average,-0.037 (-4.5%),-0.036 (-4.5%),0.074 (70.4%),0.053 (37.0%)

In [ ]:
medical_df['Low_Medium'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
37,Low,Medium,CPP,-0.047 (-5.7%),-0.123 (-15.3%),0.105 (50.6%),0.315 (149.8%)
38,Low,Medium,EPP,-0.113 (-13.7%),-0.083 (-10.3%),-0.072 (-36.0%),-0.110 (-52.3%)
43,Low,Medium,ROC,-0.011 (-1.3%),-0.015 (-1.8%),-0.097 (-47.1%),-0.087 (-40.9%)
42,Low,Medium,PSTA,-0.009 (-1.0%),-0.022 (-2.7%),-0.129 (-63.3%),-0.115 (-54.5%)
39,Low,Medium,FACT,-0.068 (-8.2%),-0.061 (-7.6%),0.303 (147.4%),0.094 (44.7%)
40,Low,Medium,GSTAR,-0.117 (-14.1%),-0.054 (-6.6%),-0.088 (-42.3%),-0.107 (-50.2%)
41,Low,Medium,MAB,-0.028 (-3.4%),-0.008 (-1.1%),-0.012 (-5.7%),-0.013 (-6.6%)
44,Low,Medium,Average,-0.056 (-6.8%),-0.052 (-6.5%),0.001 (0.5%),-0.003 (-1.4%)