In [ ]:
import pandas as pd
import numpy as np
import os
import pickle

file_path = 'Add_XGB_DNN_Trade-off_overall_data_non_medical.pkl'
with open(file_path, 'rb') as f:
    non_medical_df = pickle.load(f)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
non_medical_df['Overall_Overall'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
64,Overall,Overall,CPP,-0.025 (-3.8%),-0.046 (-6.3%),0.008 (8.8%),0.041 (35.6%)
65,Overall,Overall,EPP,-0.065 (-10.5%),-0.044 (-6.1%),-0.062 (-46.5%),-0.077 (-49.4%)
70,Overall,Overall,ROC,-0.022 (-2.7%),0.040 (5.4%),-0.039 (-31.9%),-0.012 (2.9%)
69,Overall,Overall,PSTA,0.003 (0.5%),-0.009 (-1.3%),-0.027 (-18.3%),-0.015 (-4.2%)
66,Overall,Overall,FACT,-0.258 (-40.5%),-0.128 (-17.4%),0.098 (109.6%),0.041 (50.0%)
67,Overall,Overall,GSTAR,-0.168 (-26.6%),-0.086 (-11.4%),-0.061 (-52.1%),-0.083 (-58.8%)
68,Overall,Overall,MAB,-0.070 (-11.0%),-0.025 (-3.1%),0.002 (0.5%),-0.022 (-16.3%)
71,Overall,Overall,Average,-0.086 (-13.5%),-0.043 (-5.8%),-0.011 (-4.3%),-0.018 (-5.8%)

In [ ]:
non_medical_df['High_High'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
1,High,High,CPP,-0.015 (-2.8%),-0.011 (-1.5%),-0.029 (-29.9%),-0.036 (-34.5%)
2,High,High,EPP,-0.147 (-26.2%),-0.032 (-4.4%),-0.062 (-64.8%),-0.081 (-77.2%)
7,High,High,ROC,0.006 (1.3%),0.140 (19.2%),-0.065 (-69.7%),0.044 (43.8%)
6,High,High,PSTA,0.007 (1.4%),0.007 (0.9%),-0.018 (-19.0%),-0.010 (-9.7%)
3,High,High,FACT,-0.542 (-96.9%),-0.247 (-33.6%),-0.049 (-56.5%),-0.049 (-41.3%)
4,High,High,GSTAR,-0.303 (-55.8%),-0.149 (-20.4%),-0.070 (-76.0%),-0.086 (-83.4%)
5,High,High,MAB,-0.144 (-25.8%),-0.082 (-11.2%),0.008 (8.5%),-0.021 (-20.5%)
8,High,High,Average,-0.163 (-29.3%),-0.053 (-7.3%),-0.041 (-43.9%),-0.034 (-31.8%)

In [ ]:
non_medical_df['Low_High'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
28,Low,High,CPP,0.003 (0.4%),-0.015 (-2.2%),0.019 (11.1%),0.067 (36.9%)
29,Low,High,EPP,-0.016 (-2.2%),-0.057 (-8.7%),-0.105 (-56.5%),-0.132 (-59.5%)
34,Low,High,ROC,-0.028 (-3.8%),-0.005 (-0.8%),-0.047 (-25.5%),-0.072 (-31.8%)
33,Low,High,PSTA,0.007 (1.1%),-0.004 (-0.6%),-0.033 (-17.9%),-0.031 (-14.0%)
30,Low,High,FACT,-0.058 (-8.1%),-0.032 (-4.8%),-0.015 (-6.6%),-0.036 (-8.8%)
31,Low,High,GSTAR,-0.094 (-13.0%),-0.019 (-3.0%),-0.045 (-24.8%),-0.088 (-39.2%)
32,Low,High,MAB,-0.027 (-3.9%),-0.001 (-0.2%),0.017 (9.4%),0.007 (4.2%)
35,Low,High,Average,-0.030 (-4.2%),-0.019 (-2.9%),-0.030 (-15.8%),-0.041 (-16.0%)

In [ ]:
non_medical_df['Medium_Low'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
46,Medium,Low,CPP,-0.037 (-5.5%),-0.093 (-12.8%),0.037 (32.2%),0.104 (88.8%)
47,Medium,Low,EPP,-0.057 (-7.7%),-0.047 (-6.2%),-0.030 (-20.1%),-0.030 (-16.8%)
52,Medium,Low,ROC,-0.035 (-4.3%),0.010 (1.4%),-0.004 (0.5%),0.013 (20.5%)
51,Medium,Low,PSTA,-0.001 (-0.1%),-0.019 (-2.5%),-0.029 (-22.9%),-0.014 (-9.1%)
48,Medium,Low,FACT,-0.207 (-27.6%),-0.106 (-14.1%),0.178 (146.4%),0.130 (114.2%)
49,Medium,Low,GSTAR,-0.117 (-15.5%),-0.076 (-9.8%),-0.072 (-57.2%),-0.084 (-58.7%)
50,Medium,Low,MAB,-0.054 (-7.0%),-0.009 (-0.6%),0.008 (11.3%),-0.031 (-14.7%)
53,Medium,Low,Average,-0.073 (-9.7%),-0.048 (-6.4%),0.013 (12.9%),0.013 (17.7%)

In [ ]:
non_medical_df['Medium_Medium'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
55,Medium,Medium,CPP,-0.049 (-7.2%),-0.066 (-8.7%),0.004 (21.9%),0.030 (51.1%)
56,Medium,Medium,EPP,-0.041 (-5.9%),-0.041 (-5.3%),-0.050 (-44.6%),-0.063 (-44.2%)
61,Medium,Medium,ROC,-0.032 (-3.9%),0.013 (1.8%),-0.040 (-32.8%),-0.031 (-21.1%)
60,Medium,Medium,PSTA,-0.002 (-0.3%),-0.022 (-3.1%),-0.027 (-13.4%),-0.007 (16.1%)
57,Medium,Medium,FACT,-0.225 (-29.3%),-0.125 (-16.9%),0.281 (355.2%),0.119 (136.1%)
58,Medium,Medium,GSTAR,-0.156 (-22.1%),-0.099 (-12.4%),-0.054 (-50.5%),-0.073 (-54.1%)
59,Medium,Medium,MAB,-0.054 (-7.0%),-0.009 (-0.6%),-0.025 (-27.1%),-0.045 (-34.2%)
62,Medium,Medium,Average,-0.080 (-10.8%),-0.050 (-6.4%),0.013 (29.8%),-0.010 (7.1%)