In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')
import pickle
# Save the filtered_dfs dictionary
file_path = '/content/drive/My Drive/2024/Project_5/Results/Add_XGB_DNN_Trade-off_overall_data.pkl'
# Load the filtered_dfs dictionary
with open(file_path, 'rb') as f:
    overall_df = pickle.load(f)

Mounted at /content/drive

In [2]:
# Define the method replacements
method_replacements = {
    'cpp': 'CPP',
    'epp': 'EPP',
    'fact': 'FACT',
    'gstar': 'GSTAR',
    'multiaccboost': 'MAB',
    'psta': 'PSTA',
    'roc': 'ROC',
    'All': 'Average'
}

# Define the desired order
method_order = ['CPP', 'EPP', 'ROC', 'PSTA', 'FACT', 'GSTAR', 'MAB', 'Average']

# Apply filtering, renaming, and sorting to all keys in overall_df
for key in overall_df.keys():
    # Filter out 'baseline'
    overall_df[key] = overall_df[key].query("method != 'baseline'").copy()

    # Rename methods
    overall_df[key]['method'] = overall_df[key]['method'].replace(method_replacements)

    # Convert 'method' column to categorical with the specified order
    overall_df[key]['method'] = pd.Categorical(overall_df[key]['method'], categories=method_order, ordered=True)

    # Sort by the new categorical order
    overall_df[key] = overall_df[key].sort_values('method')

In [3]:
overall_df['Overall_Overall'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
64,Overall,Overall,CPP,-0.037 (-6.9%),-0.056 (-7.5%),-0.000 (0.1%),0.060 (36.2%)
65,Overall,Overall,EPP,-0.064 (-11.2%),-0.054 (-7.2%),-0.079 (-46.3%),-0.092 (-51.6%)
70,Overall,Overall,ROC,-0.015 (-1.9%),0.014 (2.1%),-0.065 (-37.2%),-0.049 (-19.0%)
69,Overall,Overall,PSTA,-0.002 (-0.5%),-0.010 (-1.3%),-0.056 (-33.9%),-0.042 (-20.2%)
66,Overall,Overall,FACT,-0.231 (-51.0%),-0.142 (-19.3%),0.091 (88.4%),0.022 (33.4%)
67,Overall,Overall,GSTAR,-0.111 (-18.2%),-0.062 (-8.2%),-0.075 (-41.7%),-0.088 (-42.2%)
68,Overall,Overall,MAB,-0.096 (-28.8%),-0.069 (-9.4%),-0.032 (-24.7%),-0.048 (-36.1%)
71,Overall,Overall,Average,-0.079 (-16.9%),-0.054 (-7.3%),-0.031 (-13.6%),-0.034 (-14.2%)

In [4]:
overall_df['High_High'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
1,High,High,CPP,-0.060 (-11.2%),-0.040 (-5.5%),-0.011 (-16.4%),-0.041 (-26.8%)
2,High,High,EPP,-0.137 (-25.0%),-0.066 (-8.9%),-0.148 (-67.4%),-0.180 (-78.1%)
7,High,High,ROC,-0.013 (-2.4%),0.056 (7.8%),-0.141 (-66.2%),-0.098 (-19.6%)
6,High,High,PSTA,-0.001 (-0.1%),0.007 (0.9%),-0.061 (-31.5%),-0.045 (-22.4%)
3,High,High,FACT,-0.537 (-98.5%),-0.238 (-32.3%),-0.179 (-84.7%),-0.194 (-79.9%)
4,High,High,GSTAR,-0.224 (-41.9%),-0.119 (-16.3%),-0.150 (-68.2%),-0.178 (-74.5%)
5,High,High,MAB,-0.137 (-25.0%),-0.091 (-12.2%),-0.033 (-12.6%),-0.089 (-36.4%)
8,High,High,Average,-0.159 (-29.2%),-0.070 (-9.5%),-0.103 (-49.6%),-0.118 (-48.2%)

In [5]:
overall_df['High_Low'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
10,High,Low,CPP,-0.002 (-1.0%),-0.014 (-1.9%),-0.036 (-40.7%),-0.023 (-34.6%)
11,High,Low,EPP,-0.008 (-4.2%),-0.024 (-3.4%),-0.037 (-36.9%),-0.027 (-39.0%)
16,High,Low,ROC,-0.012 (-6.8%),0.005 (0.7%),-0.036 (-43.3%),-0.013 (-13.2%)
15,High,Low,PSTA,-0.001 (-0.7%),-0.000 (0.0%),-0.014 (-35.6%),0.001 (-4.5%)
12,High,Low,FACT,-0.179 (-100.0%),-0.217 (-30.2%),-0.070 (-100.0%),-0.046 (-100.0%)
13,High,Low,GSTAR,-0.002 (-0.9%),-0.011 (-1.6%),0.006 (17.7%),0.009 (42.5%)
14,High,Low,MAB,-0.171 (-95.4%),-0.215 (-30.0%),-0.066 (-92.4%),-0.044 (-94.1%)
17,High,Low,Average,-0.054 (-29.9%),-0.068 (-9.5%),-0.036 (-47.3%),-0.020 (-34.7%)

In [6]:
overall_df['High_Medium'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
19,High,Medium,CPP,-0.060 (-18.0%),-0.045 (-6.4%),-0.122 (-62.9%),-0.091 (-54.0%)
20,High,Medium,EPP,-0.061 (-18.5%),-0.043 (-6.2%),-0.132 (-71.8%),-0.129 (-80.4%)
25,High,Medium,ROC,0.021 (8.8%),0.032 (5.5%),-0.112 (-61.5%),-0.074 (-37.3%)
24,High,Medium,PSTA,-0.005 (-1.4%),-0.000 (0.0%),-0.104 (-55.3%),-0.079 (-49.2%)
21,High,Medium,FACT,-0.332 (-84.5%),-0.204 (-28.5%),-0.033 (-1.9%),-0.009 (69.7%)
22,High,Medium,GSTAR,-0.078 (-21.6%),-0.051 (-7.3%),-0.130 (-68.4%),-0.118 (-70.8%)
23,High,Medium,MAB,-0.201 (-60.3%),-0.150 (-20.7%),-0.112 (-60.1%),-0.116 (-68.8%)
26,High,Medium,Average,-0.102 (-27.9%),-0.066 (-9.1%),-0.106 (-54.5%),-0.088 (-41.5%)

In [7]:
overall_df['Medium_Low'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
46,Medium,Low,CPP,-0.037 (-5.5%),-0.093 (-12.8%),0.037 (32.2%),0.104 (88.8%)
47,Medium,Low,EPP,-0.057 (-7.7%),-0.047 (-6.2%),-0.030 (-20.1%),-0.030 (-16.8%)
52,Medium,Low,ROC,-0.035 (-4.3%),0.010 (1.4%),-0.004 (0.5%),0.013 (20.5%)
51,Medium,Low,PSTA,-0.001 (-0.1%),-0.019 (-2.5%),-0.029 (-22.9%),-0.014 (-9.1%)
48,Medium,Low,FACT,-0.207 (-27.6%),-0.106 (-14.1%),0.178 (146.4%),0.130 (114.2%)
49,Medium,Low,GSTAR,-0.117 (-15.5%),-0.076 (-9.8%),-0.072 (-57.2%),-0.084 (-58.7%)
50,Medium,Low,MAB,-0.054 (-7.0%),-0.009 (-0.6%),0.008 (11.3%),-0.031 (-14.7%)
53,Medium,Low,Average,-0.073 (-9.7%),-0.048 (-6.4%),0.013 (12.9%),0.013 (17.7%)

In [8]:
overall_df['Medium_Medium'][['class_imbalance_degree', 'unprivileged_representation_degree','method', 'F1-score', 'BAcc', 'EOp', 'EOd']]

,class_imbalance_degree,unprivileged_representation_degree,method,F1-score,BAcc,EOp,EOd
55,Medium,Medium,CPP,-0.049 (-7.2%),-0.066 (-8.7%),0.004 (21.9%),0.030 (51.1%)
56,Medium,Medium,EPP,-0.041 (-5.9%),-0.041 (-5.3%),-0.050 (-44.6%),-0.063 (-44.2%)
61,Medium,Medium,ROC,-0.032 (-3.9%),0.013 (1.8%),-0.040 (-32.8%),-0.031 (-21.1%)
60,Medium,Medium,PSTA,-0.002 (-0.3%),-0.022 (-3.1%),-0.027 (-13.4%),-0.007 (16.1%)
57,Medium,Medium,FACT,-0.225 (-29.3%),-0.125 (-16.9%),0.281 (355.2%),0.119 (136.1%)
58,Medium,Medium,GSTAR,-0.156 (-22.1%),-0.099 (-12.4%),-0.054 (-50.5%),-0.073 (-54.1%)
59,Medium,Medium,MAB,-0.054 (-7.0%),-0.009 (-0.6%),-0.025 (-27.1%),-0.045 (-34.2%)
62,Medium,Medium,Average,-0.080 (-10.8%),-0.050 (-6.4%),0.013 (29.8%),-0.010 (7.1%)